// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyFRrencGjyOJ3rEx10CqTlqhqU3-2o0',
    appId: '1:374262604171:web:b26a21c526d0cea14a8f8e',
    messagingSenderId: '374262604171',
    projectId: 'bookswap-887d4',
    authDomain: 'bookswap-887d4.firebaseapp.com',
    storageBucket: 'bookswap-887d4.firebasestorage.app',
    measurementId: 'G-WVCL3RTJ3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuBh_B21uU8pDLNbQ-3a5zaLyYkn5fWA',
    appId: '1:374262604171:android:6d0f909007085aba4a8f8e',
    messagingSenderId: '374262604171',
    projectId: 'bookswap-887d4',
    storageBucket: 'bookswap-887d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGX0joRK0oUvYkTwoWGAHOF9pcssJnCQ',
    appId: '1:374262604171:ios:ebfa2b05abbd7bf44a8f8e',
    messagingSenderId: '374262604171',
    projectId: 'bookswap-887d4',
    storageBucket: 'bookswap-887d4.firebasestorage.app',
    iosBundleId: 'com.example.bookswappApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHGX0joRK0oUvYkTwoWGAHOF9pcssJnCQ',
    appId: '1:374262604171:ios:ebfa2b05abbd7bf44a8f8e',
    messagingSenderId: '374262604171',
    projectId: 'bookswap-887d4',
    storageBucket: 'bookswap-887d4.firebasestorage.app',
    iosBundleId: 'com.example.bookswappApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyFRrencGjyOJ3rEx10CqTlqhqU3-2o0',
    appId: '1:374262604171:web:c9f8fd7782f64d9b4a8f8e',
    messagingSenderId: '374262604171',
    projectId: 'bookswap-887d4',
    authDomain: 'bookswap-887d4.firebaseapp.com',
    storageBucket: 'bookswap-887d4.firebasestorage.app',
    measurementId: 'G-GGTN5LSPQ4',
  );
}
